# Site settings
title: "Alter Lagos"
email:
description: "Apuntes sobre informática y tecnología en general"
baseurl: ""
url: "http://alagos.github.io"
title_description: "Apuntes sobre informática y tecnología en general"
title_image: "http://www.gravatar.com/avatar/bac3b43b389e58d49f8b4a30bd0cf96a?s=500&d=mm"
google_analytics: "UA-63804433-1"
disqus_account: alagos
#github_repository:
#addthis_id:
post_limit: 5

# Social usernames/URLs
twitter_username: nomesigaporfa
github_username:  alagos
linkedin_link: https://cl.linkedin.com/in/alterlagos
#google_plus_link:
stackoverflow_link: http://stackoverflow.com/users/895789/alter-lagos

# Footer
#footer_left: "Made with <i class=\"fa fa-heart\"></i> by <a href=\"https://twitter.com/_JacobTomlinson\">Jacob Tomlinson</a>"
#footer_right: "&lt;/&gt; on <a href=\"https://github.com/jacobtomlinson/carte-noire\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]
permalink: pretty
exclude: [vendor]
